### ISSUE TITLE
Mini Fab doesnt seem to work with color="primary"

### ISSUE THREAD

**Issue by northkode** [hperrin/svelte-material-ui#55] opened 2019-10-29 22:30 UTC
Cant seem to get the fab buttons to respect the color primary attribute. 
It always shows secondary no matter what

Attached is the outputted markup after initializing the button like so:

```
<Fab color="primary" variant="raised" mini>
    <Icon class="material-icons" style="margin-right: 0px;">remove_red_eye</Icon>
</Fab>
```
You can see in the screen shot it does have the primary class on it, but the outputted css is mdc-theme-secondary

![Screenshot 2019-10-29 16 29 32](https://user-images.githubusercontent.com/6988083/67814303-51a83900-fa69-11e9-99de-bd37abd72618.png)

**Comment by MintyMods** [comment] 2019-12-07 18:08
I tested this using the same code sample:-

```
<Fab color="primary" variant="raised" mini>
  <Icon class="fad fa-eye" style="margin-right: 0px;" />
</Fab>
```

 and it works as expected:-

![fab](https://user-images.githubusercontent.com/2349765/70378511-04956d80-1919-11ea-8717-73a2166e6ccd.gif)

Changing the [markup to secondary](https://svelte.dev/repl/dcb26caddfaf4385a700f402d5497898?version=3.16.0) also works.

Could your issue be that your styles are coming from the _mixin.scss (as shown in your screenshot) 
![image](https://user-images.githubusercontent.com/2349765/70378675-2263d200-191b-11ea-8f74-74ee79c24ee8.png)


rather than a processed stylesheet?

![image](https://user-images.githubusercontent.com/2349765/70378722-b2a21700-191b-11ea-89cd-f01418903007.png)

If not are you able to reproduce the issue within the following [Repl](https://svelte.dev/repl/dcb26caddfaf4385a700f402d5497898?version=3.16.0) or show your code?

**Comment by hperrin** [comment] 2021-04-15 20:44
I have checked with the current version, and I can't reproduce, so I'm going to close this issue:

https://sveltematerialui.com/demo/fab/

**Closed by hperrin** 2021-04-15 20:44 UTC
