### ISSUE TITLE
Textfield has error when value is null

### ISSUE THREAD

**Issue by romanown** [hperrin/svelte-material-ui#212] opened 2021-03-16 11:25 UTC
i use. when value is null i have error bellow.
```
 <Textfield
                value={props}
                label="label"
              />
```

```
TypeError: can't access property "addEventListener", e.input_ is null
    registerInteractionHandler
```
when i use as bellow is fine. but bind i can not use.

```
<Textfield
                value={props || ""}
                label="label"
              />
```
is error when compile
` ValidationError: Can only bind to an identifier (e.g. `foo`) or a member expression (e.g. `foo.bar` or `foo[baz]`)`
if i use
```
<Textfield
                bind:value={props || ""}
                label="label"
              />
```

**Comment by hperrin** [comment] 2021-04-23 18:20
Duplicate of #143.

**Closed** 2021-04-23 18:20 UTC
Labels: duplicate

**Comment by romanown** [comment] 2021-04-23 20:51
in the specified request, the header says error when using the bind. I wrote that with any null error. I am glad that after at least more than six months, the problem has been fixed.

**Comment by hperrin** [comment] 2021-04-24 15:18
Yeah, sorry for the delay. I haven't had any time to work on the project until recently.
