### ISSUE TITLE
Issues regarding checkbox in data table

### ISSUE THREAD

**Issue by iXyles** [hperrin/svelte-material-ui#61] opened 2019-11-08 22:54 UTC
In the example: https://github.com/hperrin/svelte-material-ui/blob/master/site/src/routes/demo/data-table.svelte there is an example of how to use checkboxes in a data table if you want to group them by the header.

My question is, what if I want a checkbox without the header thing? Because all the ways I am trying to ends up throwing errors in the console, example 
```
Uncaught (in promise) TypeError: Cannot read property 'querySelector' of null 
Uncaught TypeError: Cannot read property '2' of undefined
````

Is this maybe a bug.. or am I missing something?

**Comment by iXyles** [comment] 2019-11-16 14:36
Found something else along it

```component.js:96 Uncaught TypeError: Cannot read property 'checked' of undefined
    at Object.isCheckboxAtRowIndexChecked (component.js:96)
    at t.handleRowCheckboxChange (foundation.js:150)
    at HTMLTableSectionElement.handleRowCheckboxChange_ (component.js:47)
```
So I am guessing this is a bug of some kind or that it should be "undefined" checked

**Comment by MintyMods** [comment] 2019-12-07 16:53
Testing this out with the following simplified sample of the demo code I do not see your issue:-

```
<DataTable>
  <Body>
    {#each options as option (option.name)}
      <Row>
        <Cell checkbox>
          <Checkbox
            bind:group={selected}
            value={option}
            valueKey={option.name} />
        </Cell>
        <Cell>{option.name}</Cell>
        <Cell>{option.description}</Cell>
        <Cell numeric>{option.price}</Cell>
      </Row>
    {/each}
  </Body>
</DataTable>
```
The table is displayed correctly and the check-boxes work as expected:-

![datatable](https://user-images.githubusercontent.com/2349765/70377908-f42dc480-1911-11ea-9287-228c0fa32ac1.gif)

Are you able to create a [Repl ](https://svelte.dev/repl/hello-world?version=3.16.0) showing the issue?

**Comment by iXyles** [comment] 2019-12-07 17:32
Check the output in console :)

**Comment by MintyMods** [comment] 2019-12-07 18:51
Ah OK, I get a different error but the same problem where it tries to obtain the header component to attach the onChange listener:-


![image](https://user-images.githubusercontent.com/2349765/70379015-9e601900-191f-11ea-8607-767cab27da45.png)


This is failing within the MDC code and checking the documentation for Material Components shows the header to be a `mandatory` part of the markup  (possibly as the header is used for other reasons) :-


![image](https://user-images.githubusercontent.com/2349765/70379218-de280000-1921-11ea-8865-ebe9f547fde5.png)


So I guess you need to hide the header rather than simply removing it from the markup or you could raise an issue against MDC.

P.S. I did try to create a [specific repl ](https://svelte.dev/repl/ca8684474d7149aa93dcf3e3dca8fef7?version=3.16.0) showing the issue but seem to have hit a bug with the Svelte Repl which is now [fixed](https://github.com/sveltejs/svelte/issues/4034) but not yet live.

**Comment by iXyles** [comment] 2019-12-07 19:52
This is the error I am experiencing for an example:
![image](https://user-images.githubusercontent.com/5310286/70379884-2ac80700-1933-11ea-8cd0-489256ab3ad8.png)

```
<DataTable table$aria-label="Licenses">
  <Head>
    <Row>
      <Cell>#Id</Cell>
      <Cell>Active</Cell>
      <Cell>Tag</Cell>
      <Cell>Key</Cell>
      <Cell>Type</Cell>
      <Cell>Edit</Cell>
      <Cell>Delete</Cell>
    </Row>
  </Head>
  <Body>
    <Row>
      <Cell>SOME ID</Cell>
      <Cell>
        <Switch bind:checked={license.active} /><!-- normally I've an "on:click" part here too-->
      </Cell>
      <Cell>tag</Cell>
      <Cell>key</Cell>
      <Cell>service</Cell>
      <Cell>
        <Button variant="raised"><Label>Edit</Label></Button><!-- normally I've an "on:click" part here too-->
      </Cell>
      <Cell>
        <Button variant="raised"<Label>Remove</Label></Button><!-- normally I've an "on:click" part here too-->
      </Cell>
    </Row>
  </Body>
</DataTable>
```

**Comment by MintyMods** [comment] 2019-12-07 22:17
Ah OK, you do have the header. I have put your sample code into a [Repl](https://svelte.dev/repl/ca8684474d7149aa93dcf3e3dca8fef7?version=3.15.0) showing the error

**Comment by iXyles** [comment] 2019-12-07 22:20
Yep, both of them! :) 
![image](https://user-images.githubusercontent.com/5310286/70381307-2eb25400-1948-11ea-8c21-e81ada4d6e8a.png)

**Comment by hperrin** [comment] 2019-12-09 19:10
Ok, I know what’s going on, I think. I have code telling checkboxes not to initialize inside of data tables, because the table is supposed to instantiate the component.

**Comment by axtn** [comment] 2019-12-30 16:17
What would be a solution to this? I get the same cannot read checked of undefined as well when adding a row to the table.
Do I have to manually refresh the layout?

**Comment by Egnus** [comment] 2020-02-23 18:14
I had the same issue and I discovered that everything happen because of how `DataTable` Svelte Component is written.
Since this works with a promise where every row is subscribed (not in a observable way) to the Table, if your rows changes over time, or if your rows are not available at the Table component runtime, the checkbox will fail.
This is a Bug and here is the test case happening:
https://svelte.dev/repl/d9624fd3be3b4caea409f5a151aaf457?version=3.15.0

In the above, since `delayedData` is initially false and therefore Rows are loaded after 5s.
Everything will look fine, but the component is broken (_see console_), the checkbox in the header and at the row are not connected, and from here the content might stop loading more items anymore.
If you change `delayedData` initially to true, everything will be ok and the checkbox will be linked.

A workaround is to set the data from the condition `{#if delayedData}` outside the table, and Render the entire table each time the data changes (by setting the condition to false).
Check this REPL that do the workaround (in 15s a second row will be added and all checkbox will still work as expected)
https://svelte.dev/repl/77b086932159463bae0ebfc214df9bd4?version=3.15.0

_This workaround is a very bad approach, **against what SVELTE core was designed for**, for this kind of full rendering behaviours we should go back to REACT._

Please we need a fix for this @hperrin

**Comment by hperrin** [comment] 2020-02-26 19:17
A possible solution would be a prop for the data table telling it not to block checkboxes. It seems hacky, but at least that would provide a solution.

**Comment by hperrin** [comment] 2020-02-26 19:20
I don’t believe the underlying MDC component is designed to add/remove rows, but if the component is never instantiated, and we’re only using the styling for it, I don’t think it would be a problem. Let me try that out and see if there are any unintended consequences.

**Comment by MintyMods** [comment] 2020-02-26 19:52
> A possible solution would be a prop for the data table telling it not to block checkboxes. It seems hacky, but at least that would provide a solution.

If it's optional, It will be fine, we will test it, _and all the rest_, don't worry...

 :o)

**Comment by darryl-snow** [comment] 2020-04-12 06:01
Best option I've found so far - just use the data table css, not the js:

```
<table class="mdc-data-table__table " aria-label="Ingredients">
  <tbody class="mdc-data-table__content ">
    {#each things as thing}
        <tr class=" mdc-data-table__row" aria-selected="false">
          <td class="mdc-data-table__cell">{thing.name}</td>
          <td class="mdc-data-table__cell">{thing.size}</td>
          <td class="mdc-data-table__cell">
            <Checkbox />
          </td>
        </tr>
    {/each}
  </tbody>
</table>

<script>
  import '@smui/data-table/bare.css'
  import Checkbox from '@smui/checkbox'

  let things = [...]
</script>
```

**Comment by unlocomqx** [comment] 2020-10-09 07:27
If you have an input inside a cell, add event.stopPropagation() to the change event to avoid the 'checked' error.

`<input on:change|stopPropagation use:upload bind:this={file_input}...`

It's not a real solution but it avoids the error for now

**Comment by bynjamin** [comment] 2021-02-18 14:02
We had similar problem, with adding new rows to datatable. We solved the issue by using datatable API which is unfortunately not documented anywhere. Firstly on every change of items array call the table.layout() method which rerenders checkboxes and get rid of errors. Don't forget to use tick() function to wait for DOM changes to complete. Secondly use data-row-id prop on Row component and rely on table.getSelectedRowIds() method to get checked items. Check the example below :)

`<script>
  import { tick } from 'svelte';
  import DataTable, { Head, Body, Row, Cell } from '@smui/data-table';
  import Checkbox from '@smui/checkbox';
  import Actions from './archiveRecordActions.svelte';

  export let items;

  let table;
  let selected = [];

  // Bug in SMUI library: Need to rerender table layout after change of table items
  // Github issue: https://github.com/hperrin/svelte-material-ui/issues/61
  const rerenderTableLayout = async () => {
    await tick();
    table.layout();
  };

  // Need to rely on internal material.io logic and get selected items from table API,
  // because SMUI logic is broken after table items change
  const handleCheckboxChange = () => {
    selected = table.getSelectedRowIds();
  };
</script>

  <AddRow on:add="{rerenderTableLayout}" />
  <DataTable bind:this="{table}" >
    <Head>
      <Row>
        <Cell checkbox>
          <Checkbox />
        </Cell>
        <Cell>
          Name
        </Cell>
      </Row>
    </Head>
    <Body>
      {#each items as item (item.id)}
        <Row class="table-row" data-row-id="{item.id}">
          <Cell checkbox>
            <Checkbox value="{item}" valueKey="{item.id}" on:change="{handleCheckboxChange}" />
          </Cell>
          <Cell>
            {item.name}
          </Cell>
        </Row>
      {/each}
    </Body>
  </DataTable>

**Comment by hperrin** [comment] 2021-11-10 05:48
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.

**Closed by hperrin** 2021-11-10 05:48 UTC
Labels: bug
