### ISSUE TITLE
TypeScript Error "Not all code paths return a value."

### ISSUE THREAD

**Issue by major-mayer** [hperrin/svelte-material-ui#514] opened 2022-09-28 08:41 UTC
**Describe the bug**
When running `npm run check` on my project that uses svelte-material-ui, the following error appears:

```
/path/to/my/project/node_modules/@smui/common/src/internal/dispatch.ts:1:17
Error: Not all code paths return a value. 
export function dispatch<T extends any = any>(
  element: Element,
```

**To Reproduce**
1. Install a component that needs stuff from @smui/common
2. Run `npm run check`

**Expected behavior**
No error should appear.

**Screenshots**
the error from above appears.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Irrelevant since no error (yet) on runtime
 - Version Irrelavant

**Additional context**

**Comment by Cobrand** [comment] 2022-10-01 13:33
You also need `compilerOptions.noImplicitReturns` to be true in `tsconfig.json`.

Can be fixed by adding `return undefined` after line 29 of dispatch.ts, but I'm not sure whether or not this is the right fix.

**Comment by major-mayer** [comment] 2022-10-04 08:13
I created a small PR to fix this. Let's see if it gets accepted

**Comment by DetachHead** [comment] 2022-11-04 07:58
while it's probably a good idea to fix this, after some investigating i noticed that this is caused by `typesVersions` in the `@smui/common` package incorrectly pointing to the source code.

ideally your code should not be typechecking the function implementations in this package. see #532

**Comment by hperrin** [comment] 2023-04-03 20:29
This is now fixed here: https://github.com/hperrin/svelte-material-ui/commit/c55145231e1350eaf38b1e2ec79b17c9a0f76ca4#diff-54062c270ea651b890f69db1e1c4243b2c9033075870d648ab407cca159b67b7

**Closed by hperrin** 2023-04-03 20:29 UTC
Labels: bug
