### ISSUE TITLE
Cannot read properties of null (reading 'SmuiElement') in SvelteKit with Snackbar

### ISSUE THREAD

**Issue by jdgamble555** [hperrin/svelte-material-ui#535] opened 2022-11-05 17:44 UTC
**Describe the bug**
I updated to the latest version and I get this error while using Snackbar:

```
TypeError: Cannot read properties of null (reading 'SmuiElement')
    at CommonLabel.svelte:35:23
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1871:22)
    at Object.default (/src/components/message.svelte:42:95)
    at eval (/node_modules/@smui/snackbar/dist/Snackbar.svelte:210:36)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1871:22)
    at eval (/src/components/message.svelte:27:103)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1871:22)
    at eval (/src/routes/+layout.svelte:42:95)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1871:22)
    at root.svelte:41:37
Cannot read properties of null (reading 'SmuiElement')
TypeError: Cannot read properties of null (reading 'SmuiElement')
    at CommonLabel.svelte:35:23
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1871:22)
    at Object.default (/src/components/message.svelte:42:95)
    at eval (/node_modules/@smui/snackbar/dist/Snackbar.svelte:210:36)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1871:22)
    at eval (/src/components/message.svelte:27:103)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1871:22)
    at eval (/src/routes/+layout.svelte:42:95)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1871:22)
    at root.svelte:41:37
Cannot read properties of null (reading 'SmuiElement')
TypeError: Cannot read properties of null (reading 'SmuiElement')
    at CommonLabel.svelte:35:23
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1871:22)
    at Object.default (/src/components/message.svelte:42:95)
    at eval (/node_modules/@smui/snackbar/dist/Snackbar.svelte:210:36)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1871:22)
    at eval (/src/components/message.svelte:27:103)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1871:22)
    at eval (/src/routes/+layout.svelte:42:95)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:1871:22)
    at root.svelte:41:37
```

And **message.svelte**
```html
<script lang="ts">
	import Snackbar, { Actions, Label } from '@smui/snackbar';
	import IconButton from '@smui/icon-button';
	import { snackbar, snackmsg } from '$lib/stores';
</script>

<Snackbar bind:this={$snackbar} labelText={$snackmsg} timeoutMs={4000}>
	<Label />
	<Actions>
		<IconButton class="material-icons" title="Dismiss">close</IconButton>
	</Actions>
</Snackbar>
```

**Expected behavior**
No errors or 500 Server Error.

**Additional context**
Work around is to check for browser:

```html
{#if browser}
	<Message />
{/if}
```
But this should be done internally, potentially have a pseudo document object on serverside.

J

**Comment by NickantX** [comment] 2022-11-06 05:41
The snackbar store is undefined until the client-side router kicks in to bind the component instance to the store. This is expected behavior from Svelte and unrelated to SMUI.

**Comment by jdgamble555** [comment] 2022-11-09 02:36
@NickantX - This is not expected. Other UI Frameworks work fine in SvelteKit without having to crash.

**Comment by hperrin** [comment] 2023-04-03 22:23
I believe this is caused by an incorrect TypeScript configuration. I have no issues with using SMUI in SvelteKit. I'm going to close as a duplicate of #524. We can discuss there.

**Closed by hperrin** 2023-04-03 22:23 UTC
Labels: bug

**Comment by jdgamble555** [comment] 2023-04-04 02:33
You can close this for me. I have done so many changes since this was open, but seems to be fixed when I remove the check for browser now. I have no idea how if got fixed.

Thanks for getting back to this package!

J

**Comment by raythurnevoid** [comment] 2023-04-04 21:19
Most likely fixed vite side.
