### ISSUE TITLE
Chips: shouldRemoveOnTrailingIconClick

### ISSUE THREAD

**Issue by ispyinternet** [hperrin/svelte-material-ui#57] opened 2019-10-30 15:29 UTC
Is this functionality only meant to apply with Sets (i.e currently not working with standalone chip)?

**Comment by MintyMods** [comment] 2019-12-07 17:06
No idea why yet but if I specify the value of the attribute as follows:-

```
      <Chip
        shouldRemoveOnTrailingIconClick="false"
```

Then the chip is still removed when clicking the icon. 

But changing my usage to the same as the online demo code that works:-

```
      <Chip
        shouldRemoveOnTrailingIconClick={false}
```

Resolves the issue in my case.

**Comment by ispyinternet** [comment] 2019-12-09 11:24
The page? But yh, I was just playing around - so unsure if this is expected.

**Comment by MintyMods** [comment] 2019-12-09 15:31
Ah OK, I asked so that I can reproduce the issue but I am not sure that use case is valid. 

The [material chip](https://material.io/components/chips/#usage) component support various types of usage but these mostly involve having the chip within a list. The current SMUI examples are all used with the parent `Set` (and the current `Chip` component doesn't contain any removal logic).

The documentation does mention some placements:-

> Input chips can be integrated with other components. They can appear:
> 
> - Inline with the text input cursor in a field
> - In a stacked list
> - In a horizontally scrollable list

The 'inline within a field' kind of suggests it could be used without the set but I am not sure without testing it.

I guess you could use a set (consisting of a single item) or code the removal of the chip yourself. See the following [Repl](https://svelte.dev/repl/bf2255f8c9e24b5d94b2e98157b4a31d?version=3.15.0)

**Comment by hperrin** [comment] 2021-11-10 05:46
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.

**Closed by hperrin** 2021-11-10 05:46 UTC
