### ISSUE TITLE
Select resets value if no option matches

### ISSUE THREAD

**Issue by JJK96** [hperrin/svelte-material-ui#183] opened 2020-11-03 09:38 UTC
I have the following setup, I have a select box which is initialized with an empty list of options.
Then I load the options asynchronously and they are updated.
When the options are loaded, the `value` of the select is set to the first option.

When printing the `value` of the select, I see that it is first set to the correct value, but then overwritten with `''`.

When I use the default `<select>` component instead of `<Select>` this problem does not occur.

I was able to get the correct behaviour in this case using the following patch:

```patch
diff --git a/node_modules/@smui/select/Select.svelte b/node_modules/@smui/select/Select.svelte
index a3a6843..5f32f57 100644
--- a/node_modules/@smui/select/Select.svelte
+++ b/node_modules/@smui/select/Select.svelte
@@ -11,7 +11,6 @@
     {withLeadingIcon ? 'mdc-select--with-leading-icon' : ''}
     {invalid ? 'mdc-select--invalid' : ''}
   "
-  on:MDCSelect:change={changeHandler}
   {...exclude($$props, ['use', 'class', 'ripple', 'disabled', 'enhanced', 'variant', 'noLabel', 'withLeadingIcon', 'label', 'value', 'selectedIndex', 'selectedText', 'dirty', 'invalid', 'updateInvalid', 'required', 'input$', 'label$', 'ripple$', 'outline$', 'menu$', 'list$'])}
 >
   <slot name="icon"></slot>
@@ -56,6 +55,7 @@
       id={inputId}
       on:change
       on:input
+      bind:value
       {...exclude(prefixFilter($$props, 'input$'), ['use', 'class'])}
     ><slot></slot></select>
   {/if}
```

I'm not submitting this patch as a PR since it probably breaks some other behaviour that I am not currently using.

**Comment by hperrin** [comment] 2021-11-10 06:18
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.

**Closed by hperrin** 2021-11-10 06:18 UTC

**Comment by kolmakova** [comment] 2021-11-25 12:07
Still can reproduce even in v6. I think that the problem is that `list` of `select/src/Select.svelte` is not being updated if the new options were mount, unlike the `value`, that updates every time it was passed to the component.

[Here](https://github.com/hperrin/svelte-material-ui/blob/f715bc1f20450dd6b17c15dcc4e208069a16c97a/packages/select/src/Select.svelte#L194) the list is being updated only once on mount:
```svelte
<List
  ...
  on:SMUIList:mount={(event) => (list = event.detail)}
  ...
>
</List>
```
[And here](https://github.com/hperrin/svelte-material-ui/blob/master/packages/select/src/Select.svelte#L550), a function that gets the values from that `list`. It is being used in code to find a `value` by index, so if the current `list` doesn't contain an updated `value`, `value` becomes undefined, for example it happens [here](https://github.com/hperrin/svelte-material-ui/blob/f715bc1f20450dd6b17c15dcc4e208069a16c97a/packages/select/src/Select.svelte#L350).
```svelte
function getMenuItemValues() {
  return list.getOrderedList().map((accessor) => accessor.getValue());
}
```
