### ISSUE TITLE
TypeError: _this.input_ is null with Textfield

### ISSUE THREAD

**Issue by rafalou38** [hperrin/svelte-material-ui#206] opened 2021-02-21 13:44 UTC
When I use any text field:
```html
<script>
	import Textfield from "@smui/textfield";
</script>

<Textfield label="Username" />
```
I get this error:
```
Uncaught (in promise) TypeError: _this.input_ is null
    registerInteractionHandler component.js:444
    registerRootHandlers_ foundation.js:212
    registerRootHandlers_ foundation.js:211
    init foundation.js:110
    MDCComponent component.js:36
    MDCRipple component.js:32
    rippleFactory component.js:48
    createRipple_ component.js:448
    initialize component.js:93
    MDCComponent component.js:32
    MDCTextField component.js:42
    5 Textfield.svelte:166
    run index.mjs:18
    mount_component index.mjs:1415
    flush index.mjs:746
    init index.mjs:1501
    App client.96115843.js:1563
    render app.mjs:424
    fulfilled app.mjs:25
    promise callback*step app.mjs:27
    __awaiter app.mjs:28
    __awaiter app.mjs:24
    render app.mjs:408
    1 app.mjs:403
    fulfilled app.mjs:25
    promise callback*step app.mjs:27
    __awaiter app.mjs:28
    __awaiter app.mjs:24
    handle_target$1 app.mjs:389
    navigate app.mjs:207
    __awaiter app.mjs:28
    __awaiter app.mjs:24
    navigate app.mjs:195
    load_current_page app.mjs:58
    promise callback*load_current_page app.mjs:53
    start$1 app.mjs:357
    <anonymous> client.ts:3
component.js:444:218
```

I have installed:
```json
{
	"devDependencies": {
		"@smui/textfield": "^2.0.0-beta.0",
	}
}
```

I also added 
```js
warning.code !== "a11y-label-has-associated-control" ||
```
as shown in #202

how can I use Text fields?

**Comment by certara-munderhill** [comment] 2021-02-22 16:40
@rafalou38 - Think you'll need to do a bind:value={variableName} before the TextField will be visible.

**Comment by rafalou38** [comment] 2021-03-07 16:57
Thanks it worked!!

**Comment by hperrin** [comment] 2021-04-23 18:21
Duplicate of #143.

**Closed by hperrin** 2021-04-23 18:21 UTC
Labels: duplicate
