### ISSUE TITLE
mdc-ripple-line and label incorrect transform

### ISSUE THREAD

**Issue by mcw0805** [hperrin/svelte-material-ui#109] opened 2020-03-07 08:39 UTC
Hello, 
I am new to Svelte and the Svelte Material UI. 

I was using the `Textfield` component, and I'm noticing some issues with the classes applied when focused.

![image](https://user-images.githubusercontent.com/25259190/76139853-65206d80-6022-11ea-8840-a9fb0a0edac3.png)

As seen above, the purple line is not in line with the black line, but I'm not seeing that. In addition, the label is also way too close to the input field. It seems from the demo that the label should translate a few pixels on focus. I've looked at the code for the demo to see if there were any styling differences, but it seemed to be not doing much either.

Versions:
- "svelte": "^3.0.0",
- "svelte-material-ui": "^1.0.0-beta.20"

I have import using this statement: `import Textfield from '@smui/textfield';`
and then I do `<Textfield variant="filled" bind:value={someNumber} label="Label"  />` below the script tag. I have no other custom css stylings.

I'm not sure what's going on in my situation. and I also apologize that I haven't looked deeply into the commit history for this.

**Comment by smundro** [comment] 2020-03-07 19:17
Confirmed in mac Firefox and Chrome.  Clean install of svelte/smui with no other CSS and the text field ripple is off.  Disabling inline-flex on the label appears to align active state better, but empty state text appears off.

**Comment by VolodymyrKornetskyi** [comment] 2020-03-09 14:33
Insert `@import "@smui/textfield/style";` in `_smui-theme.scss`

**Comment by mcw0805** [comment] 2020-03-10 04:01
> Insert `@import "@smui/textfield/style";` in `_smui-theme.scss`

hmm... I don't think this changed anything. I'm also not too familiar with how sass compliation works :/

**Comment by adwellj** [comment] 2020-04-17 19:54
I'm seeing this issue as well. Has anyone had luck in finding a solution?

**Comment by adwellj** [comment] 2020-04-17 20:10
I just found the offending style for me, which may be for others if you're building this on top of the svelte template.

public/global.css has a rule on line 36 to apply 0.5em of bottom margin to the input. Dealing with that rule got everything to line up like on the Text Field demo page.

**Comment by hperrin** [comment] 2021-11-10 05:57
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.

**Closed by hperrin** 2021-11-10 05:57 UTC
