### ISSUE TITLE
Could snackbars not be cleaned up properly?

### ISSUE THREAD

**Issue by mwamp** [hperrin/svelte-material-ui#53] opened 2019-10-29 15:45 UTC
Symptom : 
`TypeError: node.parentNode is null` when changing page.

One of my pages will show a snackbar under certain circumstances, if I try to leave the page, I get a TypeError from index.mjs (main svelte context dies)

Any idea where this could come from?

I have tried without success (without expecting any either...)
```
onDestroy(()=>{
 delete var_bound_to_snackbar_dom
})
```

**Comment by hperrin** [comment] 2019-11-07 21:19
I'd have to see your code to figure out what's going on.

**Comment by perliedman** [comment] 2020-01-04 10:14
Hi @hperrin! I think I might have the same issue, removing a `Snackbar` component in my app causes this error:

```
Uncaught (in promise) TypeError: Cannot read property 'removeChild' of null
    at detach (index.mjs:161)
    at Object.d (Button.svelte:25)
    at Object.d (Label.svelte:14)
    at destroy_component (index.mjs:1311)
    at Object.d (Snack.svelte:23)
    at Object.d (Snackbar.svelte:12)
    at destroy_component (index.mjs:1311)
    at Object.d (Snack.svelte:20)
    at destroy_component (index.mjs:1311)
    at Object.d (Snack.svelte:16)
```

A repo (based on `smui-example-rollup`) containing the quite basic code to reproduce this is here: https://github.com/perliedman/smui-snackbar-issue

Hope this helps!

(BTW, thanks for all the work with `smui`, it's been a great help getting started with Svelte!)

**Comment by rothnic** [comment] 2020-03-15 04:15
I ran into this same issue. It is really hard to debug what is going on in the client.

* It appears that svelte tries to remove the snackbar from the parent container of the page (_layout)
* It then appears to remove any child elements from snackbar
* It then tries to remove snackbar from its parent, but at this point it no longer has a parent

I was able to work around this issue by wrapping the snackbar in another div, so that it isn't removed on the first step I outlined.

So, this does work: 

```
<svelte:head>
  <title>{store.name}</title>
</svelte:head>

<div>
  <Snackbar bind:this={mySnackbar}>
    <Label>Copied {text} to clipboard!</Label>
  </Snackbar>
</div>
```

This doesn't work:

```
<svelte:head>
  <title>{store.name}</title>
</svelte:head>

<Snackbar bind:this={mySnackbar}>
   <Label>Copied {text} to clipboard!</Label>
</Snackbar>
```

**Comment by hperrin** [comment] 2021-11-10 05:45
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.

**Closed by hperrin** 2021-11-10 05:45 UTC
Labels: question
