### ISSUE TITLE
Standard Select Enhanced dropdown is not repositioned after scroll or resize

### ISSUE THREAD

**Issue by bwbroersma** [hperrin/svelte-material-ui#20] opened 2019-08-23 19:54 UTC
Screenshot of an open dropdown of a Standard Select Enhanced in a Mozilla Firefox nightly (70.0a1 (2019-08-20) (64-bit)) left and a Google Chrome (Version 76.0.3809.100 (Official Build) (64-bit)) right after resize & scroll:
![image](https://user-images.githubusercontent.com/4252918/63619549-3d6e3880-c5ef-11e9-80cf-eddb48021c85.png)

**Comment by hperrin** [comment] 2019-08-23 21:07
Good catch.

**Comment by MintyMods** [comment] 2019-10-26 12:01
I don't seem to be able to reproduce this against v71.0b4 of Firefox. @bwbroersma can you confirm if this is still failing you and provided info on how to reproduce.
Thanks

**Comment by MintyMods** [comment] 2019-10-31 22:21
@bwbroersma Thank you, I miss understood the original issue.

Just so I am clear then, the issue is that the options do not move with the select when the window is resized, scrolled, etc. 

![smui](https://user-images.githubusercontent.com/2349765/67989951-5a953800-fc2c-11e9-9362-68117d28e177.gif)

Leading to the options being detached from the original select control.

**Comment by hperrin** [comment] 2019-11-07 20:34
I'm not sure what to do on this one. It doesn't appear that MDC gives me any way to fix the positioning. It may be better to raise an issue on that project instead.

**Comment by bwbroersma** [comment] 2019-11-07 23:22
Ok https://material-components.github.io/material-components-web-catalog/#/component/select got the same issue.

BTW https://www.muicss.com/docs/v1/react/select behavior/solution is just to close the menu on resize (and disable scroll on open).
https://material.io/components/menus/#exposed-dropdown-menu defines the dropdown/select behavior that is not correct in MDC I think.

**Comment by MintyMods** [comment] 2019-11-08 16:46
I didn't get anywhere with this either. From what I could tell the problem is caused by the menu being appended/moved to the body. It could be re-positioned using Javascript but agree the issue seems to be with the underlying components.

**Comment by hperrin** [comment] 2019-11-08 19:21
I did happen to find another bug in the pursuit of this one. The menu being hoisted to the body was causing it to stay in the DOM after the component was destroyed. As for this one, I'll leave it open as a reminder to track the bug in upstream. @bwbroersma, do you want to file a bug in the MDC repo, or should I?

**Comment by bwbroersma** [comment] 2019-11-14 13:31
I cannot reproduce it on https://material-components.github.io/material-components-web-catalog/#/component/select because upstream is fixed!
See https://github.com/material-components/material-components-web/issues/5002
So we need to update to MDC 4.0 and it should be fixed in SMUI too.

**Comment by hperrin** [comment] 2021-11-10 05:42
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.

**Closed by hperrin** 2021-11-10 05:42 UTC
Labels: bug
