### ISSUE TITLE
Load CSS before DOM on https://sveltematerialui.com/

### ISSUE THREAD

**Issue by lud** [hperrin/svelte-material-ui#74] opened 2019-12-04 17:17 UTC
When viewing the demo website, the unstyled content appears for a short time before the styles are loaded.

I wonder if this is easily fixable or if this problem will be in my apps too ?

Thank you

**Comment by MintyMods** [comment] 2019-12-07 16:15
I do not have this issue when using the components locally or online ([demo](https://www.mintymods.info/demo/)) so I would not worry about your own usage in regards to how the demo site performs.  My site is obviously still very much in beta but it uses quite a few of the components and all (besides a couple of known issues) are displayed perfectly.

You can also try out the components yourself in the Svelte [repl](https://svelte.dev/repl/dcb26caddfaf4385a700f402d5497898?version=3.16.0)

**Comment by MintyMods** [comment] 2019-12-07 19:33
Possibly the same issue as #66 so may depend on using Sapper which I do not.

**Comment by lud** [comment] 2019-12-08 02:31
Well the point is that the project demo has a big flash of no-CSS before loading and it will hurt the project adoption !

**Comment by hperrin** [comment] 2019-12-13 22:39
It does look to be a Sapper only issue. Not sure what's causing it.

**Comment by hperrin** [comment] 2019-12-13 22:39
Closing as duplicate of #66.

**Closed by hperrin** 2019-12-13 22:39 UTC
Labels: duplicate
